Разметка главной страницы.
htmlacademy-adaptive/1799851-cat-energy-23 pull request #7
Opened 2021-07-23 20:33 UTC by chernii5k

2021-07-23 21:08 UTC, Ankhena requested changes

2021-07-23 21:08 UTC, Ankhena commented on source/index.html
> +      <img class="page-header__logo-mobile" src="img/index--img/logo-mobile.svg" width="34" height="38"
`index--img`
Почему ты решил так называть папку?

2021-07-23 21:08 UTC, Ankhena commented on source/index.html
> +          <li class="site-list__item site-list__item-current">
`site-list__item site-list__item-current`
зачем тут микс из двух элементов?

2021-07-23 21:08 UTC, Ankhena commented on source/index.html
> +      <div class="main-nav__center">
`main-nav__center`
На мобилках меню выпадает вниз, на десктопах и планшетах справа. 
Почему класс называется center?
И какое назначение у этой обертки?

2021-07-23 21:08 UTC, Ankhena commented on source/index.html
> +          </h3>
Расскажи, пожалуйста, про свой выбор h1, h2 и h3.
Почему ты считаешь, заголовок из макета не годится для h1?

2021-07-23 21:08 UTC, Ankhena commented on source/index.html
> +            alt="Баночка питания с нежной курицей для вашего кота!">
Это отличные alt

2021-07-23 21:08 UTC, Ankhena commented on source/index.html
> +            <p class="advantages__description">
Тут вполне можно обойтись без лишнего `p`

2021-07-23 21:10 UTC, Ankhena requested changes

2021-07-23 21:10 UTC, Ankhena commented on source/index.html
> +                <img src="img/index--img/arrow.png" width="32" height="10" alt="Стрелка перехода">
Почему ты считаешь эти изображения контентными?

2021-07-24 06:14 UTC, chernii5k commented on source/index.html
> +      <img class="page-header__logo-mobile" src="img/index--img/logo-mobile.svg" width="34" height="38"
хотел разделить папки с файлами картинок для разных страниц. нужно все в одной папке держать?

2021-07-24 06:18 UTC, chernii5k commented on source/index.html
> +    <p class="page-header__shop"><span class="page-footer__shop--bold">Cat</span> energy</p>
не футер, да, исправил. 
Логотип является ссылкой только на внутренних страницах.
А на главной иконка и название магазина

2021-07-24 06:20 UTC, chernii5k commented on source/index.html
> +    <p class="page-header__shop"><span class="page-footer__shop--bold">Cat</span> energy</p>
так написано в ТЗ

2021-07-24 06:21 UTC, chernii5k commented on source/index.html
> +                <img src="img/index--img/arrow.png" width="32" height="10" alt="Стрелка перехода">
ошибся, сейчас исправлю

2021-07-24 06:25 UTC, chernii5k commented on source/index.html
> +          <input class="before-after_toggle" id="fatcat" type="range">
исправил)

2021-07-25 09:57 UTC, merged